export const SocketEvents = {
    JOIN_LOBBY: "JOIN_LOBBY",
    CREATE_LOBBY: "CREATE_LOBBY",
    ENTER_LOBBY: "ENTER_LOBBY",
    USER_JOINED_LOBBY: "USER_JOINED_LOBBY",
    TOGGLE_PLAYER_STATUS: "TOGGLE_PLAYER_STATUS",
    LOBBY_UPDATED: "LOBBY_UPDATED",
    SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
    RECEIVE_CHAT_MESSAGE: "RECEIVE_CHAT_MESSAGE"
};
