const LobbySocketEvents = {
    JOIN_LOBBY: "JOIN_LOBBY",
    CREATE_LOBBY: "CREATE_LOBBY",
    ENTER_LOBBY: "ENTER_LOBBY",
    USER_JOINED_LOBBY: "USER_JOINED_LOBBY",
    TOGGLE_PLAYER_STATUS: "TOGGLE_PLAYER_STATUS",
    LOBBY_UPDATED: "LOBBY_UPDATED",
    NAVIGATE_TO_GAME: "NAVIGATE_TO_GAME",
    BACK_TO_THE_LOBBY: "BACK_TO_THE_LOBBY",
    NAVIGATE_TO_LOBBY: "NAVIGATE_TO_LOBBY",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED"
}
const ChatSocketEvents = {
    SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
    RECEIVE_CHAT_MESSAGE: "RECEIVE_CHAT_MESSAGE",
}

const VoiceSocketEvents = {
    JOIN_VOICE_REQUEST: "JOIN_VOICE_REQUEST",
    NEW_VOICE_USER_JOINED: "NEW_VOICE_USER_JOINED",
    EXISTING_VOICE_USER_JOINED: "EXISTING_VOICE_USER_JOINED",
    SEND_ICE_CANDIDATE: "SEND_ICE_CANDIDATE",
    SEND_OFFER: "SEND_OFFER",
    RECEIVE_ICE_CANDIDATE: "RECEIVE_ICE_CANDIDATE",
    RECEIVE_OFFER: "RECEIVE_OFFER",
    RECEIVE_ANSWER: "RECEIVE_ANSWER",
    SEND_ANSWER: "SEND_ANSWER",
    VOICE_USER_LEFT: "VOICE_USER_LEFT",
}

const TicTacToeSocketEvents = {
    CREATE_GAME_1: "CREATE_GAME_1",
    START_GAME_1: "START_GAME_1",
    TTT_MOVE_1: "TTT_MOVE_1",
    TTT_GAME_UPDATE_1: "TTT_GAME_UPDATE_1",
    TTT_GAME_OVER_1: "TTT_GAME_OVER_1",
    TTT_GAME_RESTART_1: "TTT_GAME_RESTART_1"
}
const LandSocketEvents = {
    CREATE_GAME_4: "CREATE_GAME_4",
    START_GAME_4: "START_GAME_4"
}
export const SocketEvents = {
    ...LobbySocketEvents,
    ...ChatSocketEvents,
    ...TicTacToeSocketEvents,
    ...VoiceSocketEvents,
    ...LandSocketEvents
};

